name: Automation

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Add Jira issue type as label
      uses: ./
      if: ${{ github.actor != 'dependabot[bot]' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        jira-base-url: ${{ secrets.JIRA_BASE_URL }}
        jira-username: ${{ secrets.JIRA_USERNAME }}
        jira-token: ${{ secrets.JIRA_ACCESS_TOKEN }}
        jira-project-key: CTR

    - name: Assign labels, reviewers and owner
      uses: contractify/label-and-assign@v2
      if: ${{ github.actor != 'dependabot[bot]' }}
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
